[destination.databricks.credentials]
catalog = "<configure me>" # fill this in!
server_hostname = "<configure me>" # fill this in!
http_path = "<configure me>" # fill this in!
access_token = "<configure me>" # fill this in!
client_id = "<configure me>" # fill this in!
client_secret = "<configure me>" # fill this in!